# Generated by Django 4.1.3 on 2022-12-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libManage', '0004_book_genre_book_price_book_url_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(default=None, null=True, upload_to='images/book/'),
        ),
    ]
