# Generated by Django 4.1.3 on 2022-12-06 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libManage', '0007_category_remove_book_url_img_book_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='libManage.category'),
        ),
    ]
